import { firebaseConfig, ADMIN_DEMO_PASSWORD } from './firebase-config.js';
const hasFirebase=!!firebaseConfig.apiKey; let db=null, fb=null, selectedSession=null; const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s); function toast(t){const el=$('#toast');el.textContent=t;el.style.display='block';setTimeout(()=>el.style.display='none',2200)} function esc(s=''){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]))}
async function initFb(){if(!hasFirebase)return; fb=await import('https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js'); const appMod=await import('https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js'); const app=appMod.initializeApp(firebaseConfig); db=fb.getFirestore(app)}
function login(){ if($('#adminPw').value===ADMIN_DEMO_PASSWORD || hasFirebase){ localStorage.setItem('sj_admin_login','1'); $('#loginBox').hidden=true; $('#dash').hidden=false; loadAll(); } else toast('비밀번호가 올바르지 않습니다.') }
function logout(){ localStorage.removeItem('sj_admin_login'); location.reload() }
function localData(){ const inq=JSON.parse(localStorage.getItem('sj_inquiries')||'[]'); const chats=JSON.parse(localStorage.getItem('sj_chats')||'[]'); const todayKey='sj_today_'+new Date().toISOString().slice(0,10); return {inq,chats,total:Number(localStorage.getItem('sj_total')||0),today:Number(localStorage.getItem(todayKey)||0),online:Math.floor(Math.random()*5)+1} }
function renderStats(d){ ['todayCount','vToday'].forEach(id=>$('#'+id).textContent=d.today.toLocaleString()); ['totalCount','vTotal'].forEach(id=>$('#'+id).textContent=d.total.toLocaleString()); ['onlineCount','vOnline'].forEach(id=>$('#'+id).textContent=d.online.toLocaleString()); $('#newInquiryCount').textContent=d.inq.filter(x=>!x.read).length; }
function inqHtml(x){return `<div class="item ${x.read?'':'unread'}"><h3>${esc(x.company||'회사명 없음')} · ${esc(x.manager||'담당자 없음')}</h3><div class="meta">${new Date(x.createdAt||Date.now()).toLocaleString('ko-KR')} · ${esc(x.category||'행사유형 미입력')} · ${esc(x.place||'장소 미입력')}</div><p>${esc(x.content||'')}</p><div class="item-actions"><button class="ghost" onclick="Admin.markRead('${x.id||''}')">읽음</button><button class="danger" onclick="Admin.delInquiry('${x.id||''}')">삭제</button></div></div>`}
function renderLocal(){ const d=localData(); renderStats(d); $('#inquiryList').innerHTML=d.inq.map(inqHtml).join('')||'<div class="item">문의가 없습니다.</div>'; $('#recentInquiries').innerHTML=d.inq.slice(0,4).map(inqHtml).join('')||'<div class="item">문의가 없습니다.</div>'; const sessions=[...new Set(d.chats.map(x=>x.sessionId))]; $('#sessionList').innerHTML=sessions.map(s=>`<div class="session ${s===selectedSession?'active':''}" onclick="Admin.selectSession('${s}')"><b>${s.slice(0,8)}</b><div class="meta">메시지 ${d.chats.filter(x=>x.sessionId===s).length}개</div></div>`).join('')||'<div class="item">상담 내역이 없습니다.</div>'; $('#recentChats').innerHTML=d.chats.slice(-4).reverse().map(c=>`<div class="item"><b>${c.role==='user'?'고객':'관리자'}</b><p>${esc(c.text)}</p></div>`).join('')||'<div class="item">상담 내역이 없습니다.</div>'; $('#visitLog').innerHTML=`<div class="item"><h3>데모 모드</h3><p>Firebase를 연결하면 최근 접속 로그가 실시간으로 표시됩니다.</p></div>`; if(selectedSession) renderChat(d.chats.filter(x=>x.sessionId===selectedSession)); }
function renderChat(list){ $('#chatTitle').textContent = selectedSession ? `상담 세션 ${selectedSession.slice(0,8)}` : '상담을 선택하세요'; $('#adminChatLog').innerHTML=list.map(m=>`<div class="bubble ${m.role==='user'?'user':'admin'}">${esc(m.text)}<div class="meta">${new Date(m.createdAt).toLocaleTimeString('ko-KR')}</div></div>`).join(''); $('#adminChatLog').scrollTop=$('#adminChatLog').scrollHeight; }
async function loadFirebase(){ const q=fb.query(fb.collection(db,'inquiries'),fb.orderBy('createdAt','desc')); fb.onSnapshot(q,snap=>{const inq=[];snap.forEach(doc=>inq.push({id:doc.id,...doc.data()})); window._inq=inq; paintFirebase();}); fb.onSnapshot(fb.query(fb.collection(db,'chats'),fb.orderBy('createdAt','asc')),snap=>{const chats=[];snap.forEach(doc=>chats.push({id:doc.id,...doc.data()})); window._chats=chats; paintFirebase();}); fb.onSnapshot(fb.collection(db,'visitors'),snap=>{const now=Date.now(), arr=[];snap.forEach(doc=>arr.push(doc.data())); const today=new Date().toISOString().slice(0,10); window._vis={total:arr.length,today:arr.filter(x=>x.date===today).length,online:arr.filter(x=>now-(x.lastSeen||0)<90000).length,logs:arr}; paintFirebase();}); }
function paintFirebase(){ const d={inq:window._inq||[],chats:window._chats||[],...(window._vis||{total:0,today:0,online:0})}; renderStats(d); $('#inquiryList').innerHTML=d.inq.map(inqHtml).join('')||'<div class="item">문의가 없습니다.</div>'; $('#recentInquiries').innerHTML=d.inq.slice(0,4).map(inqHtml).join('')||'<div class="item">문의가 없습니다.</div>'; const sessions=[...new Set(d.chats.map(x=>x.sessionId))]; $('#sessionList').innerHTML=sessions.map(s=>`<div class="session ${s===selectedSession?'active':''}" onclick="Admin.selectSession('${s}')"><b>${s.slice(0,8)}</b><div class="meta">메시지 ${d.chats.filter(x=>x.sessionId===s).length}개</div></div>`).join('')||'<div class="item">상담 내역이 없습니다.</div>'; $('#recentChats').innerHTML=d.chats.slice(-4).reverse().map(c=>`<div class="item"><b>${c.role==='user'?'고객':'관리자'}</b><p>${esc(c.text)}</p></div>`).join('')||'<div class="item">상담 내역이 없습니다.</div>'; $('#visitLog').innerHTML=(d.logs||[]).slice(-20).reverse().map(v=>`<div class="item"><h3>${esc(v.sessionId||'')}</h3><div class="meta">${new Date(v.lastSeen||Date.now()).toLocaleString('ko-KR')} · ${esc(v.path||'')}</div></div>`).join(''); if(selectedSession) renderChat(d.chats.filter(x=>x.sessionId===selectedSession)); }
async function loadAll(){ if(hasFirebase){await loadFirebase()} else {renderLocal(); setInterval(renderLocal,3000)} }
window.Admin={selectSession(s){selectedSession=s; if(hasFirebase) paintFirebase(); else renderLocal();}, async markRead(id){ if(hasFirebase&&id) await fb.updateDoc(fb.doc(db,'inquiries',id),{read:true}); else {const l=JSON.parse(localStorage.getItem('sj_inquiries')||'[]');l.forEach(x=>{if(x.id===id)x.read=true});localStorage.setItem('sj_inquiries',JSON.stringify(l));renderLocal();}}, async delInquiry(id){ if(!confirm('삭제할까요?'))return; if(hasFirebase&&id) await fb.deleteDoc(fb.doc(db,'inquiries',id)); else {let l=JSON.parse(localStorage.getItem('sj_inquiries')||'[]');l=l.filter(x=>x.id!==id);localStorage.setItem('sj_inquiries',JSON.stringify(l));renderLocal();}}};
async function reply(){ const v=$('#replyInput').value.trim(); if(!v||!selectedSession)return toast('상담 세션을 선택하세요.'); $('#replyInput').value=''; const msg={sessionId:selectedSession,text:v,role:'admin',createdAt:Date.now(),read:false}; if(hasFirebase) await fb.addDoc(fb.collection(db,'chats'),msg); else {const l=JSON.parse(localStorage.getItem('sj_chats')||'[]');l.push({...msg,id:crypto.randomUUID()});localStorage.setItem('sj_chats',JSON.stringify(l));renderLocal();} }
function seed(){ const sample={id:crypto.randomUUID(),company:'샘플기업',manager:'홍길동',category:'기업행사',place:'서울',content:'기업 워크숍 행사 문의 샘플입니다.',createdAt:Date.now(),read:false}; const l=JSON.parse(localStorage.getItem('sj_inquiries')||'[]');l.unshift(sample);localStorage.setItem('sj_inquiries',JSON.stringify(l));toast('샘플 데이터를 넣었습니다.');renderLocal() }
function clear(){ if(confirm('데모 데이터를 모두 삭제할까요?')){['sj_inquiries','sj_chats','sj_total'].forEach(k=>localStorage.removeItem(k));renderLocal()} }
function tabs(){ $$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.panel').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active');$('#pageTitle').textContent=b.textContent;}); }
async function main(){ await initFb(); $('#loginBtn').onclick=login; $('#logoutBtn').onclick=logout; $('#replyBtn').onclick=reply; $('#seedDemo').onclick=seed; $('#clearAll').onclick=clear; tabs(); if(localStorage.getItem('sj_admin_login')==='1'){$('#loginBox').hidden=true;$('#dash').hidden=false;loadAll();} }
main();
