import { firebaseConfig } from './firebase-config.js';
const hasFirebase = !!firebaseConfig.apiKey;
let db=null, fb=null, sessionId = sessionStorage.getItem('sj_session') || crypto.randomUUID();
sessionStorage.setItem('sj_session',sessionId);
async function initFb(){ if(!hasFirebase) return; fb = await import('https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js'); const appMod= await import('https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js'); const app=appMod.initializeApp(firebaseConfig); db=fb.getFirestore(app); }
function $(s){return document.querySelector(s)} function toast(t){const el=$('#toast');el.textContent=t;el.style.display='block';setTimeout(()=>el.style.display='none',2400)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]))}
function now(){return new Date().toLocaleString('ko-KR')}
async function trackVisit(){ const d=new Date().toISOString().slice(0,10); if(hasFirebase && db){ await fb.setDoc(fb.doc(db,'visitors',sessionId),{sessionId,lastSeen:Date.now(),date:d,path:location.pathname,userAgent:navigator.userAgent},{merge:true}); await fb.addDoc(fb.collection(db,'visitLogs'),{sessionId,createdAt:Date.now(),date:d,path:location.pathname}); } else { const key='sj_today_'+d; if(!sessionStorage.getItem('sj_visit')){sessionStorage.setItem('sj_visit','1');localStorage.setItem('sj_total',(Number(localStorage.getItem('sj_total')||0)+1));localStorage.setItem(key,(Number(localStorage.getItem(key)||0)+1));} }}
async function saveInquiry(data){ if(hasFirebase && db){ await fb.addDoc(fb.collection(db,'inquiries'),{...data,read:false,createdAt:Date.now()}); } else { const list=JSON.parse(localStorage.getItem('sj_inquiries')||'[]');list.unshift({...data,read:false,id:crypto.randomUUID(),createdAt:Date.now()});localStorage.setItem('sj_inquiries',JSON.stringify(list)); } }
async function addChat(text,role='user'){ const msg={sessionId,text,role,createdAt:Date.now(),read:false}; if(hasFirebase && db){ await fb.addDoc(fb.collection(db,'chats'),msg); } else { const list=JSON.parse(localStorage.getItem('sj_chats')||'[]');list.push({...msg,id:crypto.randomUUID()});localStorage.setItem('sj_chats',JSON.stringify(list)); } }
function renderLocalChat(){ const body=$('#chatBody'); const list=JSON.parse(localStorage.getItem('sj_chats')||'[]').filter(x=>x.sessionId===sessionId); body.querySelectorAll('.msg').forEach(x=>x.remove()); if(!list.length){ body.insertAdjacentHTML('beforeend',`<div class="msg bot"><b>에스제이(SJ)행사기획</b><br>무엇을 도와드릴까요?<div class="time">${now()}</div></div>`); } list.forEach(m=>body.insertAdjacentHTML('beforeend',`<div class="msg ${m.role==='user'?'me':'bot'}">${esc(m.text)}<div class="time">${new Date(m.createdAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</div></div>`)); body.scrollTop=body.scrollHeight; }
async function listenChat(){ if(hasFirebase && db){ const q=fb.query(fb.collection(db,'chats'),fb.where('sessionId','==',sessionId),fb.orderBy('createdAt','asc')); fb.onSnapshot(q,snap=>{const body=$('#chatBody'); body.querySelectorAll('.msg').forEach(x=>x.remove()); if(snap.empty) body.insertAdjacentHTML('beforeend',`<div class="msg bot"><b>에스제이(SJ)행사기획</b><br>무엇을 도와드릴까요?<div class="time">${now()}</div></div>`); snap.forEach(doc=>{const m=doc.data(); body.insertAdjacentHTML('beforeend',`<div class="msg ${m.role==='user'?'me':'bot'}">${esc(m.text)}<div class="time">${new Date(m.createdAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}</div></div>`)}); body.scrollTop=body.scrollHeight; }); } else renderLocalChat(); }
window.SJ={openChat(){ $('#chat').classList.add('open')}, closeChat(){ $('#chat').classList.remove('open')}, async sendChat(){const input=$('#chatInput'); const v=input.value.trim(); if(!v)return; input.value=''; await addChat(v,'user'); if(!hasFirebase){ setTimeout(async()=>{await addChat('문의 감사합니다. 행사 일정, 장소, 예상 인원을 남겨주시면 담당자가 확인 후 안내드리겠습니다.','admin'); renderLocalChat();},500); renderLocalChat(); }} };
async function main(){ await initFb(); await trackVisit(); setInterval(trackVisit,30000); listenChat(); $('#inquiryForm').addEventListener('submit',async e=>{e.preventDefault(); const fd=new FormData(e.target); const data=Object.fromEntries(fd.entries()); data.createdText=now(); await saveInquiry(data); e.target.reset(); toast('문의가 접수되었습니다. 관리자페이지에서 확인할 수 있습니다.');}); const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.15});document.querySelectorAll('.reveal').forEach(el=>io.observe(el)); }
main();
